; Active OPcache
opcache.enable=1
opcache.enable_cli=1

; Laravel = beaucoup de fichiers PHP → on augmente la limite
opcache.max_accelerated_files=20000

; RAM réservée à OPcache (256 Mo, tu peux réduire si ta machine est petite)
opcache.memory_consumption=256

; Taille de la mémoire pour stocker les chaînes de texte
opcache.interned_strings_buffer=16

; En prod, on ne vérifie pas les timestamps (on suppose que le code ne change pas)
opcache.validate_timestamps=0
